* Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
192.168.50.71 - - [03/Oct/2024 21:10:51] "GET /video_feed HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/usr/lib/python3/dist-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "/home/kkymin/Test_Cam/Test_Cam_v2.py", line 66, in gen_frames
    if capture_forward_400:  # 'stop' 명령을 받으면 프레임을 캡처
